stages:
  - name: generate
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        events: {stages: init, output: events, unwrap: true}
        outfilename: '{workdir}/input'
      step: {$ref: 'steps.yml#/generate'}
  - name: train
    dependencies: ['generate']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        inputdata: {stages: generate, output: inputdata, unwrap: true}
        outfile: '{workdir}/trainedbdt'
        workdir: '{workdir}'
        datasetname: 'dataA'
        jobname: 'mva'
      step: {$ref: 'steps.yml#/train'}
  - name: read
    dependencies: ['train']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        output: {stages: train, output: output, unwrap: true}
        datasetname: 'dataA'
        xmldir: {stages: train, output: xmldir, unwrap: true}
        jname: {stages: train, output: jname, unwrap: true}
        outname: '{workdir}/BDT'
      step: {$ref: 'steps.yml#/read'}
